[package]
name = "ray_tracer_rust"
version = "0.1.0"
authors = ["Antoine <antoine.desbois@usherbrooke.ca>"]

[dependencies]
image = "0.12.3"
nalgebra = "0.11"
alga = "*"
rand = "*"
num_cpus = "*"
threadpool = "*"
time = "0.1"